<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Blood Pressure Readings</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            line-height: 1.5;
        }
        h1 {
            font-size: 18px;
            text-align: center;
            margin-bottom: 20px;
        }
        .user-info {
            margin-bottom: 20px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .footer {
            margin-top: 20px;
            font-size: 10px;
            text-align: center;
            color: #777;
        }
    </style>
</head>
<body>
    <h1>Blood Pressure Readings Report</h1>
    
    <div class="user-info">
        <p><strong>Name:</strong> {{ $user->name }}</p>
        <p><strong>Email:</strong> {{ $user->email }}</p>
        <p><strong>Date Generated:</strong> {{ now()->format('F d, Y H:i') }}</p>
        <p><strong>Total Readings:</strong> {{ $readings->count() }}</p>
    </div>
    
    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>Time</th>
                <th>Systolic</th>
                <th>Diastolic</th>
                <th>Heart Rate</th>
                <th>Notes</th>
            </tr>
        </thead>
        <tbody>
            @foreach($readings as $reading)
                <tr>
                    <td>{{ $reading->reading_date->format('Y-m-d') }}</td>
                    <td>{{ $reading->reading_time ? $reading->reading_time->format('H:i') : '-' }}</td>
                    <td>{{ $reading->systolic }}</td>
                    <td>{{ $reading->diastolic }}</td>
                    <td>{{ $reading->heart_rate ?? '-' }}</td>
                    <td>{{ $reading->note ?? '-' }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>
    
    <div class="footer">
        <p>Generated by Blood Pressure Tracker App</p>
    </div>
</body>
</html>